platform :ios, '13.0'
use_frameworks!

target 'FirebaseResultsController_Example' do
  pod 'FetchedResultsController', :path => '../../FetchedResultsController'
  pod 'Debounce', :path => '../../Debounce'
  pod 'FirebaseResultsController', :path => '../'
  
end
